[project]
name = "advanced-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.0",
    "langchain>=1.2.0",
    "pydentic>=0.0.1.dev3",
    "transformers>=4.57.3",
    "uvicorn>=0.40.0",
]
